version: "3"
services:
  postcardsatrest:
    image: couchdb
    ports:
        - "5984:5984"
    restart: always

  shamlessqueue:
    image: node
    volumes:
      - ./shamelessqueue:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm run serve"
    expose:
      - "8080"
    ports:
        - "8080:8080"
    restart: always
